### ISSUE TITLE
Arduino Mega

### ISSUE THREAD

**Issue by KleinChris89** [UnfinishedBusiness/XmotionFirmware#5]
Hi very nice Job i like it. 
I have use a Open-CNC-Shield on my Workbee-Plasma from (https://blog.altholtmann.com/open-cnc-shield/) there is a Arduino Mega installed.
Do you have a Firmware that runs on the Arduino mega ?

And a other Question where do I get the ARC-OK signal that must be connected to A1 ?

Thanks

**Comment by UnfinishedBusiness** [comment]
The firmware should run on a mega with some mods though for pin mapping. It would take some doing but is possible if you want to tackle it. 

The Arc-Ok signal comes from the CNC plasma cutter. Cutters with a CNC/CPC interface will break them out there. It's just a contactor that is used to indicate if the arc has transferred to the workpiece.

Thanks
