### ISSUE TITLE
Arc OK

### ISSUE THREAD

**Issue by cadrion77** [UnfinishedBusiness/XmotionFirmware#7]
Does this use a pin for arc OK?  If so, what is it?

**Comment by UnfinishedBusiness** [comment]
Yup sure does. Pin A4 (PC1). It should be LOW when Arc Ok is active. Usually is a contactor/relay in the plasma cutting unit itself and you can switch A4 to ground. It should be pulled up internally but I do recommend a 1K resistor and a 1uF capacitor for some filtering.

**Comment by cadrion77** [comment]
Thanks for the help!

**Comment by UnfinishedBusiness** [comment]
Any time!
