### ISSUE TITLE
Changing pin configuration...

### ISSUE THREAD

**Issue by cadrion77** [UnfinishedBusiness/XmotionFirmware#8]
If I wanted to change the pin mapping around, can I do it in the cpu_map.h file or are your changes buried in the code?

**Comment by UnfinishedBusiness** [comment]
You can change any of the original GRBL pins in the cpu_map.h file but if you need to change anything pertaining to the THC (Really just the Arc OK pin or the analog input for reading arc voltage) you will have to do that in the main.c file
